// GENERATED FILE — do not hand-edit.
// Regenerate with: node scripts/generate-lucide-icon-names.mjs
// Source: lucide-react@0.479.0
//
// The full set of icons lucide-react ships, in the PascalCase form already
// used for stored icon names (e.g. "Flower2"), each paired with the
// kebab-case name lucide's DynamicIcon needs to lazily load it. Backing the
// icon picker and every icon-typed zod schema, so any name here is
// guaranteed to render — see components/icons/lucide-icon.tsx.

export const LUCIDE_ICON_NAMES = [
  "AArrowDown",
  "AArrowUp",
  "Accessibility",
  "Activity",
  "ActivitySquare",
  "Airplay",
  "AirVent",
  "ALargeSmall",
  "AlarmCheck",
  "AlarmClock",
  "AlarmClockMinus",
  "AlarmClockOff",
  "AlarmClockPlus",
  "AlarmSmoke",
  "Album",
  "AlertCircle",
  "AlertOctagon",
  "AlertTriangle",
  "AlignCenter",
  "AlignCenterHorizontal",
  "AlignCenterVertical",
  "AlignEndHorizontal",
  "AlignEndVertical",
  "AlignHorizontalDistributeCenter",
  "AlignHorizontalDistributeEnd",
  "AlignHorizontalDistributeStart",
  "AlignHorizontalJustifyCenter",
  "AlignHorizontalJustifyEnd",
  "AlignHorizontalJustifyStart",
  "AlignHorizontalSpaceAround",
  "AlignHorizontalSpaceBetween",
  "AlignJustify",
  "AlignLeft",
  "AlignRight",
  "AlignStartHorizontal",
  "AlignStartVertical",
  "AlignVerticalDistributeCenter",
  "AlignVerticalDistributeEnd",
  "AlignVerticalDistributeStart",
  "AlignVerticalJustifyCenter",
  "AlignVerticalJustifyEnd",
  "AlignVerticalJustifyStart",
  "AlignVerticalSpaceAround",
  "AlignVerticalSpaceBetween",
  "Ambulance",
  "Ampersand",
  "Ampersands",
  "Amphora",
  "Anchor",
  "Angry",
  "Annoyed",
  "Antenna",
  "Anvil",
  "Aperture",
  "Apple",
  "AppWindow",
  "AppWindowMac",
  "Archive",
  "ArchiveRestore",
  "ArchiveX",
  "AreaChart",
  "Armchair",
  "ArrowBigDown",
  "ArrowBigDownDash",
  "ArrowBigLeft",
  "ArrowBigLeftDash",
  "ArrowBigRight",
  "ArrowBigRightDash",
  "ArrowBigUp",
  "ArrowBigUpDash",
  "ArrowDown",
  "ArrowDown01",
  "ArrowDown10",
  "ArrowDownAZ",
  "ArrowDownCircle",
  "ArrowDownFromLine",
  "ArrowDownLeft",
  "ArrowDownLeftFromCircle",
  "ArrowDownLeftFromSquare",
  "ArrowDownLeftSquare",
  "ArrowDownNarrowWide",
  "ArrowDownRight",
  "ArrowDownRightFromCircle",
  "ArrowDownRightFromSquare",
  "ArrowDownRightSquare",
  "ArrowDownSquare",
  "ArrowDownToDot",
  "ArrowDownToLine",
  "ArrowDownUp",
  "ArrowDownWideNarrow",
  "ArrowDownZA",
  "ArrowLeft",
  "ArrowLeftCircle",
  "ArrowLeftFromLine",
  "ArrowLeftRight",
  "ArrowLeftSquare",
  "ArrowLeftToLine",
  "ArrowRight",
  "ArrowRightCircle",
  "ArrowRightFromLine",
  "ArrowRightLeft",
  "ArrowRightSquare",
  "ArrowRightToLine",
  "ArrowsUpFromLine",
  "ArrowUp",
  "ArrowUp01",
  "ArrowUp10",
  "ArrowUpAZ",
  "ArrowUpCircle",
  "ArrowUpDown",
  "ArrowUpFromDot",
  "ArrowUpFromLine",
  "ArrowUpLeft",
  "ArrowUpLeftFromCircle",
  "ArrowUpLeftFromSquare",
  "ArrowUpLeftSquare",
  "ArrowUpNarrowWide",
  "ArrowUpRight",
  "ArrowUpRightFromCircle",
  "ArrowUpRightFromSquare",
  "ArrowUpRightSquare",
  "ArrowUpSquare",
  "ArrowUpToLine",
  "ArrowUpWideNarrow",
  "ArrowUpZA",
  "Asterisk",
  "AsteriskSquare",
  "Atom",
  "AtSign",
  "AudioLines",
  "AudioWaveform",
  "Award",
  "Axe",
  "Axis3D",
  "Baby",
  "Backpack",
  "Badge",
  "BadgeAlert",
  "BadgeCent",
  "BadgeCheck",
  "BadgeDollarSign",
  "BadgeEuro",
  "BadgeHelp",
  "BadgeIndianRupee",
  "BadgeInfo",
  "BadgeJapaneseYen",
  "BadgeMinus",
  "BadgePercent",
  "BadgePlus",
  "BadgePoundSterling",
  "BadgeRussianRuble",
  "BadgeSwissFranc",
  "BadgeX",
  "BaggageClaim",
  "Ban",
  "Banana",
  "Bandage",
  "Banknote",
  "BarChart",
  "BarChart2",
  "BarChart3",
  "BarChart4",
  "BarChartBig",
  "BarChartHorizontal",
  "BarChartHorizontalBig",
  "Barcode",
  "Baseline",
  "Bath",
  "Battery",
  "BatteryCharging",
  "BatteryFull",
  "BatteryLow",
  "BatteryMedium",
  "BatteryPlus",
  "BatteryWarning",
  "Beaker",
  "Bean",
  "BeanOff",
  "Bed",
  "BedDouble",
  "BedSingle",
  "Beef",
  "Beer",
  "BeerOff",
  "Bell",
  "BellDot",
  "BellElectric",
  "BellMinus",
  "BellOff",
  "BellPlus",
  "BellRing",
  "BetweenHorizonalEnd",
  "BetweenHorizonalStart",
  "BetweenVerticalEnd",
  "BetweenVerticalStart",
  "BicepsFlexed",
  "Bike",
  "Binary",
  "Binoculars",
  "Biohazard",
  "Bird",
  "Bitcoin",
  "Blend",
  "Blinds",
  "Blocks",
  "Bluetooth",
  "BluetoothConnected",
  "BluetoothOff",
  "BluetoothSearching",
  "Bold",
  "Bolt",
  "Bomb",
  "Bone",
  "Book",
  "BookA",
  "BookAudio",
  "BookCheck",
  "BookCopy",
  "BookDashed",
  "BookDown",
  "BookHeadphones",
  "BookHeart",
  "BookImage",
  "BookKey",
  "BookLock",
  "Bookmark",
  "BookmarkCheck",
  "BookMarked",
  "BookmarkMinus",
  "BookmarkPlus",
  "BookmarkX",
  "BookMinus",
  "BookOpen",
  "BookOpenCheck",
  "BookOpenText",
  "BookPlus",
  "BookText",
  "BookType",
  "BookUp",
  "BookUp2",
  "BookUser",
  "BookX",
  "BoomBox",
  "Bot",
  "BotMessageSquare",
  "BotOff",
  "Box",
  "Boxes",
  "BoxSelect",
  "Braces",
  "Brackets",
  "Brain",
  "BrainCircuit",
  "BrainCog",
  "BrickWall",
  "Briefcase",
  "BriefcaseBusiness",
  "BriefcaseConveyorBelt",
  "BriefcaseMedical",
  "BringToFront",
  "Brush",
  "Bug",
  "BugOff",
  "BugPlay",
  "Building",
  "Building2",
  "Bus",
  "BusFront",
  "Cable",
  "CableCar",
  "Cake",
  "CakeSlice",
  "Calculator",
  "Calendar",
  "Calendar1",
  "CalendarArrowDown",
  "CalendarArrowUp",
  "CalendarCheck",
  "CalendarCheck2",
  "CalendarClock",
  "CalendarCog",
  "CalendarDays",
  "CalendarFold",
  "CalendarHeart",
  "CalendarMinus",
  "CalendarMinus2",
  "CalendarOff",
  "CalendarPlus",
  "CalendarPlus2",
  "CalendarRange",
  "CalendarSearch",
  "CalendarSync",
  "CalendarX",
  "CalendarX2",
  "Camera",
  "CameraOff",
  "CandlestickChart",
  "Candy",
  "CandyCane",
  "CandyOff",
  "Cannabis",
  "Captions",
  "CaptionsOff",
  "Car",
  "Caravan",
  "CarFront",
  "Carrot",
  "CarTaxiFront",
  "CaseLower",
  "CaseSensitive",
  "CaseUpper",
  "CassetteTape",
  "Cast",
  "Castle",
  "Cat",
  "Cctv",
  "ChartBarDecreasing",
  "ChartBarIncreasing",
  "ChartBarStacked",
  "ChartColumnDecreasing",
  "ChartColumnStacked",
  "ChartGantt",
  "ChartLine",
  "ChartNetwork",
  "ChartNoAxesColumnDecreasing",
  "ChartNoAxesCombined",
  "ChartNoAxesGantt",
  "ChartPie",
  "ChartScatter",
  "ChartSpline",
  "Check",
  "CheckCheck",
  "CheckCircle",
  "CheckCircle2",
  "CheckSquare",
  "CheckSquare2",
  "ChefHat",
  "Cherry",
  "ChevronDown",
  "ChevronDownCircle",
  "ChevronDownSquare",
  "ChevronFirst",
  "ChevronLast",
  "ChevronLeft",
  "ChevronLeftCircle",
  "ChevronLeftSquare",
  "ChevronRight",
  "ChevronRightCircle",
  "ChevronRightSquare",
  "ChevronsDown",
  "ChevronsDownUp",
  "ChevronsLeft",
  "ChevronsLeftRight",
  "ChevronsLeftRightEllipsis",
  "ChevronsRight",
  "ChevronsRightLeft",
  "ChevronsUp",
  "ChevronsUpDown",
  "ChevronUp",
  "ChevronUpCircle",
  "ChevronUpSquare",
  "Chrome",
  "Church",
  "Cigarette",
  "CigaretteOff",
  "Circle",
  "CircleDashed",
  "CircleDivide",
  "CircleDollarSign",
  "CircleDot",
  "CircleDotDashed",
  "CircleEllipsis",
  "CircleEqual",
  "CircleFadingArrowUp",
  "CircleFadingPlus",
  "CircleGauge",
  "CircleHelp",
  "CircleMinus",
  "CircleOff",
  "CircleParking",
  "CircleParkingOff",
  "CirclePause",
  "CirclePercent",
  "CirclePlay",
  "CirclePlus",
  "CirclePower",
  "CircleSlash",
  "CircleSlash2",
  "CircleSmall",
  "CircleStop",
  "CircleUser",
  "CircleUserRound",
  "CircleX",
  "CircuitBoard",
  "Citrus",
  "Clapperboard",
  "Clipboard",
  "ClipboardCheck",
  "ClipboardCopy",
  "ClipboardEdit",
  "ClipboardList",
  "ClipboardMinus",
  "ClipboardPaste",
  "ClipboardPenLine",
  "ClipboardPlus",
  "ClipboardType",
  "ClipboardX",
  "Clock",
  "Clock1",
  "Clock10",
  "Clock11",
  "Clock12",
  "Clock2",
  "Clock3",
  "Clock4",
  "Clock5",
  "Clock6",
  "Clock7",
  "Clock8",
  "Clock9",
  "ClockAlert",
  "ClockArrowDown",
  "ClockArrowUp",
  "Cloud",
  "CloudAlert",
  "CloudCog",
  "CloudDownload",
  "CloudDrizzle",
  "CloudFog",
  "CloudHail",
  "CloudLightning",
  "CloudMoon",
  "CloudMoonRain",
  "CloudOff",
  "CloudRain",
  "CloudRainWind",
  "CloudSnow",
  "CloudSun",
  "CloudSunRain",
  "CloudUpload",
  "Cloudy",
  "Clover",
  "Club",
  "Code",
  "Code2",
  "Codepen",
  "Codesandbox",
  "CodeSquare",
  "Coffee",
  "Cog",
  "Coins",
  "Columns",
  "Columns3",
  "Columns4",
  "Combine",
  "Command",
  "Compass",
  "Component",
  "Computer",
  "ConciergeBell",
  "Cone",
  "Construction",
  "Contact",
  "Contact2",
  "Container",
  "Contrast",
  "Cookie",
  "CookingPot",
  "Copy",
  "CopyCheck",
  "Copyleft",
  "CopyMinus",
  "CopyPlus",
  "Copyright",
  "CopySlash",
  "CopyX",
  "CornerDownLeft",
  "CornerDownRight",
  "CornerLeftDown",
  "CornerLeftUp",
  "CornerRightDown",
  "CornerRightUp",
  "CornerUpLeft",
  "CornerUpRight",
  "Cpu",
  "CreativeCommons",
  "CreditCard",
  "Croissant",
  "Crop",
  "Cross",
  "Crosshair",
  "Crown",
  "Cuboid",
  "CupSoda",
  "Currency",
  "Cylinder",
  "Dam",
  "Database",
  "DatabaseBackup",
  "DatabaseZap",
  "Delete",
  "Dessert",
  "Diameter",
  "Diamond",
  "DiamondMinus",
  "DiamondPercent",
  "DiamondPlus",
  "Dice1",
  "Dice2",
  "Dice3",
  "Dice4",
  "Dice5",
  "Dice6",
  "Dices",
  "Diff",
  "Disc",
  "Disc2",
  "Disc3",
  "DiscAlbum",
  "Divide",
  "DivideSquare",
  "Dna",
  "DnaOff",
  "Dock",
  "Dog",
  "DollarSign",
  "Donut",
  "DoorClosed",
  "DoorOpen",
  "Dot",
  "DotSquare",
  "Download",
  "DraftingCompass",
  "Drama",
  "Dribbble",
  "Drill",
  "Droplet",
  "DropletOff",
  "Droplets",
  "Drum",
  "Drumstick",
  "Dumbbell",
  "Ear",
  "EarOff",
  "Earth",
  "EarthLock",
  "Eclipse",
  "Edit",
  "Edit2",
  "Edit3",
  "Egg",
  "EggFried",
  "EggOff",
  "Ellipsis",
  "EllipsisVertical",
  "Equal",
  "EqualApproximately",
  "EqualNot",
  "EqualSquare",
  "Eraser",
  "EthernetPort",
  "Euro",
  "Expand",
  "ExternalLink",
  "Eye",
  "EyeClosed",
  "EyeOff",
  "Facebook",
  "Factory",
  "Fan",
  "FastForward",
  "Feather",
  "Fence",
  "FerrisWheel",
  "Figma",
  "File",
  "FileArchive",
  "FileAudio",
  "FileAudio2",
  "FileAxis3D",
  "FileBadge",
  "FileBadge2",
  "FileBarChart",
  "FileBarChart2",
  "FileBox",
  "FileChartLine",
  "FileChartPie",
  "FileCheck",
  "FileCheck2",
  "FileClock",
  "FileCode",
  "FileCode2",
  "FileCog",
  "FileDiff",
  "FileDigit",
  "FileDown",
  "FileEdit",
  "FileHeart",
  "FileImage",
  "FileInput",
  "FileJson",
  "FileJson2",
  "FileKey",
  "FileKey2",
  "FileLock",
  "FileLock2",
  "FileMinus",
  "FileMinus2",
  "FileMusic",
  "FileOutput",
  "FilePenLine",
  "FilePlus",
  "FilePlus2",
  "FileQuestion",
  "Files",
  "FileScan",
  "FileSearch",
  "FileSearch2",
  "FileSliders",
  "FileSpreadsheet",
  "FileStack",
  "FileSymlink",
  "FileTerminal",
  "FileText",
  "FileType",
  "FileType2",
  "FileUp",
  "FileUser",
  "FileVideo",
  "FileVideo2",
  "FileVolume",
  "FileVolume2",
  "FileWarning",
  "FileX",
  "FileX2",
  "Film",
  "Filter",
  "FilterX",
  "Fingerprint",
  "FireExtinguisher",
  "Fish",
  "FishOff",
  "FishSymbol",
  "Flag",
  "FlagOff",
  "FlagTriangleLeft",
  "FlagTriangleRight",
  "Flame",
  "FlameKindling",
  "Flashlight",
  "FlashlightOff",
  "FlaskConical",
  "FlaskConicalOff",
  "FlaskRound",
  "FlipHorizontal",
  "FlipHorizontal2",
  "FlipVertical",
  "FlipVertical2",
  "Flower",
  "Flower2",
  "Focus",
  "Folder",
  "FolderArchive",
  "FolderCheck",
  "FolderClock",
  "FolderClosed",
  "FolderCode",
  "FolderCog",
  "FolderDot",
  "FolderDown",
  "FolderEdit",
  "FolderGit",
  "FolderGit2",
  "FolderHeart",
  "FolderInput",
  "FolderKanban",
  "FolderKey",
  "FolderLock",
  "FolderMinus",
  "FolderOpen",
  "FolderOpenDot",
  "FolderOutput",
  "FolderPlus",
  "FolderRoot",
  "Folders",
  "FolderSearch",
  "FolderSearch2",
  "FolderSymlink",
  "FolderSync",
  "FolderTree",
  "FolderUp",
  "FolderX",
  "FoldHorizontal",
  "FoldVertical",
  "Footprints",
  "ForkKnife",
  "ForkKnifeCrossed",
  "Forklift",
  "FormInput",
  "Forward",
  "Frame",
  "Framer",
  "Frown",
  "Fuel",
  "Fullscreen",
  "FunctionSquare",
  "GalleryHorizontal",
  "GalleryHorizontalEnd",
  "GalleryThumbnails",
  "GalleryVertical",
  "GalleryVerticalEnd",
  "Gamepad",
  "Gamepad2",
  "GanttChartSquare",
  "Gauge",
  "Gavel",
  "Gem",
  "Ghost",
  "Gift",
  "GitBranch",
  "GitBranchPlus",
  "GitCommit",
  "GitCommitVertical",
  "GitCompare",
  "GitCompareArrows",
  "GitFork",
  "GitGraph",
  "Github",
  "Gitlab",
  "GitMerge",
  "GitPullRequest",
  "GitPullRequestArrow",
  "GitPullRequestClosed",
  "GitPullRequestCreate",
  "GitPullRequestCreateArrow",
  "GitPullRequestDraft",
  "Glasses",
  "GlassWater",
  "Globe",
  "GlobeLock",
  "Goal",
  "Grab",
  "GraduationCap",
  "Grape",
  "Grid",
  "Grid2X2",
  "Grid2X2Check",
  "Grid2X2Plus",
  "Grid2X2X",
  "Grip",
  "GripHorizontal",
  "GripVertical",
  "Group",
  "Guitar",
  "Ham",
  "Hammer",
  "Hand",
  "HandCoins",
  "HandHeart",
  "HandHelping",
  "HandMetal",
  "HandPlatter",
  "Handshake",
  "HardDrive",
  "HardDriveDownload",
  "HardDriveUpload",
  "HardHat",
  "Hash",
  "Haze",
  "HdmiPort",
  "Heading",
  "Heading1",
  "Heading2",
  "Heading3",
  "Heading4",
  "Heading5",
  "Heading6",
  "HeadphoneOff",
  "Headphones",
  "Headset",
  "Heart",
  "HeartCrack",
  "HeartHandshake",
  "HeartOff",
  "HeartPulse",
  "Heater",
  "Hexagon",
  "Highlighter",
  "History",
  "Home",
  "Hop",
  "HopOff",
  "Hospital",
  "Hotel",
  "Hourglass",
  "HousePlug",
  "HousePlus",
  "HouseWifi",
  "IceCream",
  "IceCream2",
  "IdCard",
  "Image",
  "ImageDown",
  "ImageMinus",
  "ImageOff",
  "ImagePlay",
  "ImagePlus",
  "Images",
  "ImageUp",
  "ImageUpscale",
  "Import",
  "Inbox",
  "Indent",
  "IndentDecrease",
  "IndianRupee",
  "Infinity",
  "Info",
  "Inspect",
  "InspectionPanel",
  "Instagram",
  "Italic",
  "IterationCcw",
  "IterationCw",
  "JapaneseYen",
  "Joystick",
  "Kanban",
  "KanbanSquare",
  "KanbanSquareDashed",
  "Key",
  "Keyboard",
  "KeyboardMusic",
  "KeyboardOff",
  "KeyRound",
  "KeySquare",
  "Lamp",
  "LampCeiling",
  "LampDesk",
  "LampFloor",
  "LampWallDown",
  "LampWallUp",
  "Landmark",
  "LandPlot",
  "Languages",
  "Laptop",
  "Laptop2",
  "LaptopMinimalCheck",
  "Lasso",
  "LassoSelect",
  "Laugh",
  "Layers",
  "Layers2",
  "Layout",
  "LayoutDashboard",
  "LayoutGrid",
  "LayoutList",
  "LayoutPanelLeft",
  "LayoutPanelTop",
  "LayoutTemplate",
  "Leaf",
  "LeafyGreen",
  "Lectern",
  "LetterText",
  "Library",
  "LibraryBig",
  "LibrarySquare",
  "LifeBuoy",
  "Ligature",
  "Lightbulb",
  "LightbulbOff",
  "Link",
  "Link2",
  "Link2Off",
  "Linkedin",
  "List",
  "ListCheck",
  "ListChecks",
  "ListCollapse",
  "ListEnd",
  "ListFilter",
  "ListFilterPlus",
  "ListMinus",
  "ListMusic",
  "ListOrdered",
  "ListPlus",
  "ListRestart",
  "ListStart",
  "ListTodo",
  "ListTree",
  "ListVideo",
  "ListX",
  "Loader",
  "Loader2",
  "LoaderPinwheel",
  "Locate",
  "LocateFixed",
  "LocateOff",
  "Lock",
  "LockKeyhole",
  "LockKeyholeOpen",
  "LockOpen",
  "LogIn",
  "LogOut",
  "Logs",
  "Lollipop",
  "Luggage",
  "Magnet",
  "Mail",
  "Mailbox",
  "MailCheck",
  "MailMinus",
  "MailOpen",
  "MailPlus",
  "MailQuestion",
  "Mails",
  "MailSearch",
  "MailWarning",
  "MailX",
  "Map",
  "MapPin",
  "MapPinCheck",
  "MapPinCheckInside",
  "MapPinHouse",
  "MapPinMinus",
  "MapPinMinusInside",
  "MapPinned",
  "MapPinOff",
  "MapPinPlus",
  "MapPinPlusInside",
  "MapPinX",
  "MapPinXInside",
  "MapPlus",
  "Mars",
  "MarsStroke",
  "Martini",
  "Maximize",
  "Maximize2",
  "Medal",
  "Megaphone",
  "MegaphoneOff",
  "Meh",
  "MemoryStick",
  "Menu",
  "MenuSquare",
  "Merge",
  "MessageCircle",
  "MessageCircleCode",
  "MessageCircleDashed",
  "MessageCircleHeart",
  "MessageCircleMore",
  "MessageCircleOff",
  "MessageCirclePlus",
  "MessageCircleQuestion",
  "MessageCircleReply",
  "MessageCircleWarning",
  "MessageCircleX",
  "MessageSquare",
  "MessageSquareCode",
  "MessageSquareDashed",
  "MessageSquareDiff",
  "MessageSquareDot",
  "MessageSquareHeart",
  "MessageSquareLock",
  "MessageSquareMore",
  "MessageSquareOff",
  "MessageSquarePlus",
  "MessageSquareQuote",
  "MessageSquareReply",
  "MessageSquareShare",
  "MessageSquareText",
  "MessageSquareWarning",
  "MessageSquareX",
  "MessagesSquare",
  "Mic",
  "Mic2",
  "MicOff",
  "Microchip",
  "Microscope",
  "Microwave",
  "Milestone",
  "Milk",
  "MilkOff",
  "Minimize",
  "Minimize2",
  "Minus",
  "MinusSquare",
  "Monitor",
  "MonitorCheck",
  "MonitorCog",
  "MonitorDot",
  "MonitorDown",
  "MonitorOff",
  "MonitorPause",
  "MonitorPlay",
  "MonitorSmartphone",
  "MonitorSpeaker",
  "MonitorStop",
  "MonitorUp",
  "MonitorX",
  "Moon",
  "MoonStar",
  "Mountain",
  "MountainSnow",
  "Mouse",
  "MouseOff",
  "MousePointer",
  "MousePointer2",
  "MousePointerBan",
  "MousePointerClick",
  "MousePointerSquareDashed",
  "Move",
  "Move3D",
  "MoveDiagonal",
  "MoveDiagonal2",
  "MoveDown",
  "MoveDownLeft",
  "MoveDownRight",
  "MoveHorizontal",
  "MoveLeft",
  "MoveRight",
  "MoveUp",
  "MoveUpLeft",
  "MoveUpRight",
  "MoveVertical",
  "MSquare",
  "Music",
  "Music2",
  "Music3",
  "Music4",
  "Navigation",
  "Navigation2",
  "Navigation2Off",
  "NavigationOff",
  "Network",
  "Newspaper",
  "Nfc",
  "NonBinary",
  "Notebook",
  "NotebookPen",
  "NotebookTabs",
  "NotebookText",
  "NotepadText",
  "NotepadTextDashed",
  "Nut",
  "NutOff",
  "Octagon",
  "OctagonMinus",
  "OctagonPause",
  "OctagonX",
  "Omega",
  "Option",
  "Orbit",
  "Origami",
  "Package",
  "Package2",
  "PackageCheck",
  "PackageMinus",
  "PackageOpen",
  "PackagePlus",
  "PackageSearch",
  "PackageX",
  "Paintbrush",
  "Paintbrush2",
  "PaintBucket",
  "PaintRoller",
  "Palette",
  "Palmtree",
  "PanelBottom",
  "PanelBottomClose",
  "PanelBottomDashed",
  "PanelBottomOpen",
  "PanelLeft",
  "PanelLeftClose",
  "PanelLeftDashed",
  "PanelLeftOpen",
  "PanelRight",
  "PanelRightClose",
  "PanelRightDashed",
  "PanelRightOpen",
  "PanelsLeftBottom",
  "PanelsRightBottom",
  "PanelsTopBottom",
  "PanelTop",
  "PanelTopClose",
  "PanelTopDashed",
  "PanelTopOpen",
  "Paperclip",
  "Parentheses",
  "ParkingMeter",
  "ParkingSquare",
  "ParkingSquareOff",
  "PartyPopper",
  "Pause",
  "PawPrint",
  "PcCase",
  "Pencil",
  "PencilLine",
  "PencilOff",
  "PencilRuler",
  "PenOff",
  "Pentagon",
  "PenTool",
  "Percent",
  "PercentSquare",
  "PersonStanding",
  "PhilippinePeso",
  "Phone",
  "PhoneCall",
  "PhoneForwarded",
  "PhoneIncoming",
  "PhoneMissed",
  "PhoneOff",
  "PhoneOutgoing",
  "Pi",
  "Piano",
  "Pickaxe",
  "PictureInPicture",
  "PictureInPicture2",
  "PiggyBank",
  "Pilcrow",
  "PilcrowLeft",
  "PilcrowRight",
  "PilcrowSquare",
  "Pill",
  "PillBottle",
  "Pin",
  "PinOff",
  "Pipette",
  "PiSquare",
  "Pizza",
  "Plane",
  "PlaneLanding",
  "PlaneTakeoff",
  "Play",
  "PlaySquare",
  "Plug",
  "Plug2",
  "PlugZap",
  "Plus",
  "PlusSquare",
  "Pocket",
  "PocketKnife",
  "Podcast",
  "Pointer",
  "PointerOff",
  "Popcorn",
  "Popsicle",
  "PoundSterling",
  "Power",
  "PowerOff",
  "PowerSquare",
  "Presentation",
  "Printer",
  "PrinterCheck",
  "Projector",
  "Proportions",
  "Puzzle",
  "Pyramid",
  "QrCode",
  "Quote",
  "Rabbit",
  "Radar",
  "Radiation",
  "Radical",
  "Radio",
  "RadioReceiver",
  "RadioTower",
  "Radius",
  "RailSymbol",
  "Rainbow",
  "Rat",
  "Ratio",
  "Receipt",
  "ReceiptCent",
  "ReceiptEuro",
  "ReceiptIndianRupee",
  "ReceiptJapaneseYen",
  "ReceiptPoundSterling",
  "ReceiptRussianRuble",
  "ReceiptSwissFranc",
  "ReceiptText",
  "RectangleHorizontal",
  "RectangleVertical",
  "Recycle",
  "Redo",
  "Redo2",
  "RedoDot",
  "RefreshCcw",
  "RefreshCcwDot",
  "RefreshCw",
  "RefreshCwOff",
  "Refrigerator",
  "Regex",
  "RemoveFormatting",
  "Repeat",
  "Repeat1",
  "Repeat2",
  "Replace",
  "ReplaceAll",
  "Reply",
  "ReplyAll",
  "Rewind",
  "Ribbon",
  "Rocket",
  "RockingChair",
  "RollerCoaster",
  "Rotate3D",
  "RotateCcw",
  "RotateCcwSquare",
  "RotateCw",
  "RotateCwSquare",
  "Route",
  "RouteOff",
  "Router",
  "Rows",
  "Rows4",
  "Rss",
  "Ruler",
  "RussianRuble",
  "Sailboat",
  "Salad",
  "Sandwich",
  "Satellite",
  "SatelliteDish",
  "Save",
  "SaveAll",
  "SaveOff",
  "Scale",
  "Scale3D",
  "Scaling",
  "Scan",
  "ScanBarcode",
  "ScanEye",
  "ScanFace",
  "ScanHeart",
  "ScanLine",
  "ScanQrCode",
  "ScanSearch",
  "ScanText",
  "School",
  "School2",
  "Scissors",
  "ScissorsLineDashed",
  "ScissorsSquare",
  "ScissorsSquareDashedBottom",
  "ScreenShare",
  "ScreenShareOff",
  "Scroll",
  "ScrollText",
  "Search",
  "SearchCheck",
  "SearchCode",
  "SearchSlash",
  "SearchX",
  "Section",
  "Send",
  "SendHorizonal",
  "SendToBack",
  "SeparatorHorizontal",
  "SeparatorVertical",
  "Server",
  "ServerCog",
  "ServerCrash",
  "ServerOff",
  "Settings",
  "Settings2",
  "Shapes",
  "Share",
  "Share2",
  "Sheet",
  "Shell",
  "Shield",
  "ShieldAlert",
  "ShieldBan",
  "ShieldCheck",
  "ShieldClose",
  "ShieldEllipsis",
  "ShieldHalf",
  "ShieldMinus",
  "ShieldOff",
  "ShieldPlus",
  "ShieldQuestion",
  "ShieldUser",
  "Ship",
  "ShipWheel",
  "Shirt",
  "ShoppingBag",
  "ShoppingBasket",
  "ShoppingCart",
  "Shovel",
  "ShowerHead",
  "Shrink",
  "Shrub",
  "Shuffle",
  "Sigma",
  "SigmaSquare",
  "Signal",
  "SignalHigh",
  "SignalLow",
  "SignalMedium",
  "SignalZero",
  "Signature",
  "Signpost",
  "SignpostBig",
  "Siren",
  "SkipBack",
  "SkipForward",
  "Skull",
  "Slack",
  "Slash",
  "SlashSquare",
  "Slice",
  "Sliders",
  "SlidersHorizontal",
  "Smartphone",
  "SmartphoneCharging",
  "SmartphoneNfc",
  "Smile",
  "SmilePlus",
  "Snail",
  "Snowflake",
  "Sofa",
  "Soup",
  "Space",
  "Spade",
  "Sparkle",
  "Sparkles",
  "Speaker",
  "Speech",
  "SpellCheck",
  "SpellCheck2",
  "Spline",
  "Split",
  "SplitSquareHorizontal",
  "SplitSquareVertical",
  "SprayCan",
  "Sprout",
  "Square",
  "SquareDashedBottom",
  "SquareDashedBottomCode",
  "SquareRadical",
  "SquareRoundCorner",
  "SquareSquare",
  "SquareStack",
  "SquareTerminal",
  "SquareUser",
  "SquareUserRound",
  "SquareX",
  "Squircle",
  "Squirrel",
  "Stamp",
  "Star",
  "StarHalf",
  "StarOff",
  "StepBack",
  "StepForward",
  "Stethoscope",
  "Sticker",
  "StickyNote",
  "Store",
  "StretchHorizontal",
  "StretchVertical",
  "Strikethrough",
  "Subscript",
  "Sun",
  "SunDim",
  "SunMedium",
  "SunMoon",
  "Sunrise",
  "Sunset",
  "SunSnow",
  "Superscript",
  "SwatchBook",
  "SwissFranc",
  "SwitchCamera",
  "Sword",
  "Swords",
  "Syringe",
  "Table",
  "Table2",
  "TableCellsMerge",
  "TableCellsSplit",
  "TableColumnsSplit",
  "TableOfContents",
  "TableProperties",
  "TableRowsSplit",
  "Tablet",
  "Tablets",
  "TabletSmartphone",
  "Tag",
  "Tags",
  "Tally1",
  "Tally2",
  "Tally3",
  "Tally4",
  "Tally5",
  "Tangent",
  "Target",
  "Telescope",
  "Tent",
  "TentTree",
  "Terminal",
  "TestTube",
  "TestTube2",
  "TestTubes",
  "Text",
  "TextCursor",
  "TextCursorInput",
  "TextQuote",
  "TextSearch",
  "TextSelect",
  "Theater",
  "Thermometer",
  "ThermometerSnowflake",
  "ThermometerSun",
  "ThumbsDown",
  "ThumbsUp",
  "Ticket",
  "TicketCheck",
  "TicketMinus",
  "TicketPercent",
  "TicketPlus",
  "Tickets",
  "TicketSlash",
  "TicketsPlane",
  "TicketX",
  "Timer",
  "TimerOff",
  "TimerReset",
  "ToggleLeft",
  "ToggleRight",
  "Toilet",
  "Tornado",
  "Torus",
  "Touchpad",
  "TouchpadOff",
  "TowerControl",
  "ToyBrick",
  "Tractor",
  "TrafficCone",
  "Train",
  "TrainFront",
  "TrainFrontTunnel",
  "TrainTrack",
  "Transgender",
  "Trash",
  "Trash2",
  "TreeDeciduous",
  "TreePine",
  "Trees",
  "Trello",
  "TrendingDown",
  "TrendingUp",
  "TrendingUpDown",
  "Triangle",
  "TriangleDashed",
  "TriangleRight",
  "Trophy",
  "Truck",
  "Turtle",
  "Tv",
  "Tv2",
  "TvMinimalPlay",
  "Twitch",
  "Twitter",
  "Type",
  "TypeOutline",
  "Umbrella",
  "UmbrellaOff",
  "Underline",
  "Undo",
  "Undo2",
  "UndoDot",
  "UnfoldHorizontal",
  "UnfoldVertical",
  "Ungroup",
  "Unlink",
  "Unlink2",
  "Unplug",
  "Upload",
  "Usb",
  "User",
  "User2",
  "UserCheck",
  "UserCheck2",
  "UserCog",
  "UserCog2",
  "UserMinus",
  "UserMinus2",
  "UserPen",
  "UserPlus",
  "UserPlus2",
  "UserRoundPen",
  "UserRoundSearch",
  "UserRoundX",
  "Users",
  "Users2",
  "UserSearch",
  "UserX",
  "UtilityPole",
  "Variable",
  "Vault",
  "Vegan",
  "VenetianMask",
  "Venus",
  "VenusAndMars",
  "Vibrate",
  "VibrateOff",
  "Video",
  "VideoOff",
  "Videotape",
  "View",
  "Voicemail",
  "Volleyball",
  "Volume",
  "Volume1",
  "Volume2",
  "VolumeOff",
  "VolumeX",
  "Vote",
  "Wallet",
  "Wallet2",
  "WalletCards",
  "Wallpaper",
  "Wand",
  "Wand2",
  "Warehouse",
  "WashingMachine",
  "Watch",
  "Waves",
  "WavesLadder",
  "Waypoints",
  "Webcam",
  "Webhook",
  "WebhookOff",
  "Weight",
  "Wheat",
  "WheatOff",
  "WholeWord",
  "Wifi",
  "WifiHigh",
  "WifiLow",
  "WifiOff",
  "WifiZero",
  "Wind",
  "WindArrowDown",
  "Wine",
  "WineOff",
  "Workflow",
  "Worm",
  "WrapText",
  "Wrench",
  "X",
  "Youtube",
  "Zap",
  "ZapOff",
  "ZoomIn",
  "ZoomOut",
] as const;

export type LucideIconName = (typeof LUCIDE_ICON_NAMES)[number];

export const LUCIDE_ICON_KEBAB: Record<LucideIconName, string> = {
  AArrowDown: "a-arrow-down",
  AArrowUp: "a-arrow-up",
  Accessibility: "accessibility",
  Activity: "activity",
  ActivitySquare: "square-activity",
  Airplay: "airplay",
  AirVent: "air-vent",
  ALargeSmall: "a-large-small",
  AlarmCheck: "alarm-clock-check",
  AlarmClock: "alarm-clock",
  AlarmClockMinus: "alarm-clock-minus",
  AlarmClockOff: "alarm-clock-off",
  AlarmClockPlus: "alarm-clock-plus",
  AlarmSmoke: "alarm-smoke",
  Album: "album",
  AlertCircle: "circle-alert",
  AlertOctagon: "octagon-alert",
  AlertTriangle: "triangle-alert",
  AlignCenter: "align-center",
  AlignCenterHorizontal: "align-center-horizontal",
  AlignCenterVertical: "align-center-vertical",
  AlignEndHorizontal: "align-end-horizontal",
  AlignEndVertical: "align-end-vertical",
  AlignHorizontalDistributeCenter: "align-horizontal-distribute-center",
  AlignHorizontalDistributeEnd: "align-horizontal-distribute-end",
  AlignHorizontalDistributeStart: "align-horizontal-distribute-start",
  AlignHorizontalJustifyCenter: "align-horizontal-justify-center",
  AlignHorizontalJustifyEnd: "align-horizontal-justify-end",
  AlignHorizontalJustifyStart: "align-horizontal-justify-start",
  AlignHorizontalSpaceAround: "align-horizontal-space-around",
  AlignHorizontalSpaceBetween: "align-horizontal-space-between",
  AlignJustify: "align-justify",
  AlignLeft: "align-left",
  AlignRight: "align-right",
  AlignStartHorizontal: "align-start-horizontal",
  AlignStartVertical: "align-start-vertical",
  AlignVerticalDistributeCenter: "align-vertical-distribute-center",
  AlignVerticalDistributeEnd: "align-vertical-distribute-end",
  AlignVerticalDistributeStart: "align-vertical-distribute-start",
  AlignVerticalJustifyCenter: "align-vertical-justify-center",
  AlignVerticalJustifyEnd: "align-vertical-justify-end",
  AlignVerticalJustifyStart: "align-vertical-justify-start",
  AlignVerticalSpaceAround: "align-vertical-space-around",
  AlignVerticalSpaceBetween: "align-vertical-space-between",
  Ambulance: "ambulance",
  Ampersand: "ampersand",
  Ampersands: "ampersands",
  Amphora: "amphora",
  Anchor: "anchor",
  Angry: "angry",
  Annoyed: "annoyed",
  Antenna: "antenna",
  Anvil: "anvil",
  Aperture: "aperture",
  Apple: "apple",
  AppWindow: "app-window",
  AppWindowMac: "app-window-mac",
  Archive: "archive",
  ArchiveRestore: "archive-restore",
  ArchiveX: "archive-x",
  AreaChart: "chart-area",
  Armchair: "armchair",
  ArrowBigDown: "arrow-big-down",
  ArrowBigDownDash: "arrow-big-down-dash",
  ArrowBigLeft: "arrow-big-left",
  ArrowBigLeftDash: "arrow-big-left-dash",
  ArrowBigRight: "arrow-big-right",
  ArrowBigRightDash: "arrow-big-right-dash",
  ArrowBigUp: "arrow-big-up",
  ArrowBigUpDash: "arrow-big-up-dash",
  ArrowDown: "arrow-down",
  ArrowDown01: "arrow-down-0-1",
  ArrowDown10: "arrow-down-1-0",
  ArrowDownAZ: "arrow-down-a-z",
  ArrowDownCircle: "circle-arrow-down",
  ArrowDownFromLine: "arrow-down-from-line",
  ArrowDownLeft: "arrow-down-left",
  ArrowDownLeftFromCircle: "circle-arrow-out-down-left",
  ArrowDownLeftFromSquare: "square-arrow-out-down-left",
  ArrowDownLeftSquare: "square-arrow-down-left",
  ArrowDownNarrowWide: "arrow-down-narrow-wide",
  ArrowDownRight: "arrow-down-right",
  ArrowDownRightFromCircle: "circle-arrow-out-down-right",
  ArrowDownRightFromSquare: "square-arrow-out-down-right",
  ArrowDownRightSquare: "square-arrow-down-right",
  ArrowDownSquare: "square-arrow-down",
  ArrowDownToDot: "arrow-down-to-dot",
  ArrowDownToLine: "arrow-down-to-line",
  ArrowDownUp: "arrow-down-up",
  ArrowDownWideNarrow: "arrow-down-wide-narrow",
  ArrowDownZA: "arrow-down-z-a",
  ArrowLeft: "arrow-left",
  ArrowLeftCircle: "circle-arrow-left",
  ArrowLeftFromLine: "arrow-left-from-line",
  ArrowLeftRight: "arrow-left-right",
  ArrowLeftSquare: "square-arrow-left",
  ArrowLeftToLine: "arrow-left-to-line",
  ArrowRight: "arrow-right",
  ArrowRightCircle: "circle-arrow-right",
  ArrowRightFromLine: "arrow-right-from-line",
  ArrowRightLeft: "arrow-right-left",
  ArrowRightSquare: "square-arrow-right",
  ArrowRightToLine: "arrow-right-to-line",
  ArrowsUpFromLine: "arrows-up-from-line",
  ArrowUp: "arrow-up",
  ArrowUp01: "arrow-up-0-1",
  ArrowUp10: "arrow-up-1-0",
  ArrowUpAZ: "arrow-up-a-z",
  ArrowUpCircle: "circle-arrow-up",
  ArrowUpDown: "arrow-up-down",
  ArrowUpFromDot: "arrow-up-from-dot",
  ArrowUpFromLine: "arrow-up-from-line",
  ArrowUpLeft: "arrow-up-left",
  ArrowUpLeftFromCircle: "circle-arrow-out-up-left",
  ArrowUpLeftFromSquare: "square-arrow-out-up-left",
  ArrowUpLeftSquare: "square-arrow-up-left",
  ArrowUpNarrowWide: "arrow-up-narrow-wide",
  ArrowUpRight: "arrow-up-right",
  ArrowUpRightFromCircle: "circle-arrow-out-up-right",
  ArrowUpRightFromSquare: "square-arrow-out-up-right",
  ArrowUpRightSquare: "square-arrow-up-right",
  ArrowUpSquare: "square-arrow-up",
  ArrowUpToLine: "arrow-up-to-line",
  ArrowUpWideNarrow: "arrow-up-wide-narrow",
  ArrowUpZA: "arrow-up-z-a",
  Asterisk: "asterisk",
  AsteriskSquare: "square-asterisk",
  Atom: "atom",
  AtSign: "at-sign",
  AudioLines: "audio-lines",
  AudioWaveform: "audio-waveform",
  Award: "award",
  Axe: "axe",
  Axis3D: "axis-3d",
  Baby: "baby",
  Backpack: "backpack",
  Badge: "badge",
  BadgeAlert: "badge-alert",
  BadgeCent: "badge-cent",
  BadgeCheck: "badge-check",
  BadgeDollarSign: "badge-dollar-sign",
  BadgeEuro: "badge-euro",
  BadgeHelp: "badge-help",
  BadgeIndianRupee: "badge-indian-rupee",
  BadgeInfo: "badge-info",
  BadgeJapaneseYen: "badge-japanese-yen",
  BadgeMinus: "badge-minus",
  BadgePercent: "badge-percent",
  BadgePlus: "badge-plus",
  BadgePoundSterling: "badge-pound-sterling",
  BadgeRussianRuble: "badge-russian-ruble",
  BadgeSwissFranc: "badge-swiss-franc",
  BadgeX: "badge-x",
  BaggageClaim: "baggage-claim",
  Ban: "ban",
  Banana: "banana",
  Bandage: "bandage",
  Banknote: "banknote",
  BarChart: "chart-no-axes-column-increasing",
  BarChart2: "chart-no-axes-column",
  BarChart3: "chart-column",
  BarChart4: "chart-column-increasing",
  BarChartBig: "chart-column-big",
  BarChartHorizontal: "chart-bar",
  BarChartHorizontalBig: "chart-bar-big",
  Barcode: "barcode",
  Baseline: "baseline",
  Bath: "bath",
  Battery: "battery",
  BatteryCharging: "battery-charging",
  BatteryFull: "battery-full",
  BatteryLow: "battery-low",
  BatteryMedium: "battery-medium",
  BatteryPlus: "battery-plus",
  BatteryWarning: "battery-warning",
  Beaker: "beaker",
  Bean: "bean",
  BeanOff: "bean-off",
  Bed: "bed",
  BedDouble: "bed-double",
  BedSingle: "bed-single",
  Beef: "beef",
  Beer: "beer",
  BeerOff: "beer-off",
  Bell: "bell",
  BellDot: "bell-dot",
  BellElectric: "bell-electric",
  BellMinus: "bell-minus",
  BellOff: "bell-off",
  BellPlus: "bell-plus",
  BellRing: "bell-ring",
  BetweenHorizonalEnd: "between-horizontal-end",
  BetweenHorizonalStart: "between-horizontal-start",
  BetweenVerticalEnd: "between-vertical-end",
  BetweenVerticalStart: "between-vertical-start",
  BicepsFlexed: "biceps-flexed",
  Bike: "bike",
  Binary: "binary",
  Binoculars: "binoculars",
  Biohazard: "biohazard",
  Bird: "bird",
  Bitcoin: "bitcoin",
  Blend: "blend",
  Blinds: "blinds",
  Blocks: "blocks",
  Bluetooth: "bluetooth",
  BluetoothConnected: "bluetooth-connected",
  BluetoothOff: "bluetooth-off",
  BluetoothSearching: "bluetooth-searching",
  Bold: "bold",
  Bolt: "bolt",
  Bomb: "bomb",
  Bone: "bone",
  Book: "book",
  BookA: "book-a",
  BookAudio: "book-audio",
  BookCheck: "book-check",
  BookCopy: "book-copy",
  BookDashed: "book-dashed",
  BookDown: "book-down",
  BookHeadphones: "book-headphones",
  BookHeart: "book-heart",
  BookImage: "book-image",
  BookKey: "book-key",
  BookLock: "book-lock",
  Bookmark: "bookmark",
  BookmarkCheck: "bookmark-check",
  BookMarked: "book-marked",
  BookmarkMinus: "bookmark-minus",
  BookmarkPlus: "bookmark-plus",
  BookmarkX: "bookmark-x",
  BookMinus: "book-minus",
  BookOpen: "book-open",
  BookOpenCheck: "book-open-check",
  BookOpenText: "book-open-text",
  BookPlus: "book-plus",
  BookText: "book-text",
  BookType: "book-type",
  BookUp: "book-up",
  BookUp2: "book-up-2",
  BookUser: "book-user",
  BookX: "book-x",
  BoomBox: "boom-box",
  Bot: "bot",
  BotMessageSquare: "bot-message-square",
  BotOff: "bot-off",
  Box: "box",
  Boxes: "boxes",
  BoxSelect: "square-dashed",
  Braces: "braces",
  Brackets: "brackets",
  Brain: "brain",
  BrainCircuit: "brain-circuit",
  BrainCog: "brain-cog",
  BrickWall: "brick-wall",
  Briefcase: "briefcase",
  BriefcaseBusiness: "briefcase-business",
  BriefcaseConveyorBelt: "briefcase-conveyor-belt",
  BriefcaseMedical: "briefcase-medical",
  BringToFront: "bring-to-front",
  Brush: "brush",
  Bug: "bug",
  BugOff: "bug-off",
  BugPlay: "bug-play",
  Building: "building",
  Building2: "building-2",
  Bus: "bus",
  BusFront: "bus-front",
  Cable: "cable",
  CableCar: "cable-car",
  Cake: "cake",
  CakeSlice: "cake-slice",
  Calculator: "calculator",
  Calendar: "calendar",
  Calendar1: "calendar-1",
  CalendarArrowDown: "calendar-arrow-down",
  CalendarArrowUp: "calendar-arrow-up",
  CalendarCheck: "calendar-check",
  CalendarCheck2: "calendar-check-2",
  CalendarClock: "calendar-clock",
  CalendarCog: "calendar-cog",
  CalendarDays: "calendar-days",
  CalendarFold: "calendar-fold",
  CalendarHeart: "calendar-heart",
  CalendarMinus: "calendar-minus",
  CalendarMinus2: "calendar-minus-2",
  CalendarOff: "calendar-off",
  CalendarPlus: "calendar-plus",
  CalendarPlus2: "calendar-plus-2",
  CalendarRange: "calendar-range",
  CalendarSearch: "calendar-search",
  CalendarSync: "calendar-sync",
  CalendarX: "calendar-x",
  CalendarX2: "calendar-x-2",
  Camera: "camera",
  CameraOff: "camera-off",
  CandlestickChart: "chart-candlestick",
  Candy: "candy",
  CandyCane: "candy-cane",
  CandyOff: "candy-off",
  Cannabis: "cannabis",
  Captions: "captions",
  CaptionsOff: "captions-off",
  Car: "car",
  Caravan: "caravan",
  CarFront: "car-front",
  Carrot: "carrot",
  CarTaxiFront: "car-taxi-front",
  CaseLower: "case-lower",
  CaseSensitive: "case-sensitive",
  CaseUpper: "case-upper",
  CassetteTape: "cassette-tape",
  Cast: "cast",
  Castle: "castle",
  Cat: "cat",
  Cctv: "cctv",
  ChartBarDecreasing: "chart-bar-decreasing",
  ChartBarIncreasing: "chart-bar-increasing",
  ChartBarStacked: "chart-bar-stacked",
  ChartColumnDecreasing: "chart-column-decreasing",
  ChartColumnStacked: "chart-column-stacked",
  ChartGantt: "chart-gantt",
  ChartLine: "chart-line",
  ChartNetwork: "chart-network",
  ChartNoAxesColumnDecreasing: "chart-no-axes-column-decreasing",
  ChartNoAxesCombined: "chart-no-axes-combined",
  ChartNoAxesGantt: "chart-no-axes-gantt",
  ChartPie: "chart-pie",
  ChartScatter: "chart-scatter",
  ChartSpline: "chart-spline",
  Check: "check",
  CheckCheck: "check-check",
  CheckCircle: "circle-check-big",
  CheckCircle2: "circle-check",
  CheckSquare: "square-check-big",
  CheckSquare2: "square-check",
  ChefHat: "chef-hat",
  Cherry: "cherry",
  ChevronDown: "chevron-down",
  ChevronDownCircle: "circle-chevron-down",
  ChevronDownSquare: "square-chevron-down",
  ChevronFirst: "chevron-first",
  ChevronLast: "chevron-last",
  ChevronLeft: "chevron-left",
  ChevronLeftCircle: "circle-chevron-left",
  ChevronLeftSquare: "square-chevron-left",
  ChevronRight: "chevron-right",
  ChevronRightCircle: "circle-chevron-right",
  ChevronRightSquare: "square-chevron-right",
  ChevronsDown: "chevrons-down",
  ChevronsDownUp: "chevrons-down-up",
  ChevronsLeft: "chevrons-left",
  ChevronsLeftRight: "chevrons-left-right",
  ChevronsLeftRightEllipsis: "chevrons-left-right-ellipsis",
  ChevronsRight: "chevrons-right",
  ChevronsRightLeft: "chevrons-right-left",
  ChevronsUp: "chevrons-up",
  ChevronsUpDown: "chevrons-up-down",
  ChevronUp: "chevron-up",
  ChevronUpCircle: "circle-chevron-up",
  ChevronUpSquare: "square-chevron-up",
  Chrome: "chrome",
  Church: "church",
  Cigarette: "cigarette",
  CigaretteOff: "cigarette-off",
  Circle: "circle",
  CircleDashed: "circle-dashed",
  CircleDivide: "circle-divide",
  CircleDollarSign: "circle-dollar-sign",
  CircleDot: "circle-dot",
  CircleDotDashed: "circle-dot-dashed",
  CircleEllipsis: "circle-ellipsis",
  CircleEqual: "circle-equal",
  CircleFadingArrowUp: "circle-fading-arrow-up",
  CircleFadingPlus: "circle-fading-plus",
  CircleGauge: "circle-gauge",
  CircleHelp: "circle-help",
  CircleMinus: "circle-minus",
  CircleOff: "circle-off",
  CircleParking: "circle-parking",
  CircleParkingOff: "circle-parking-off",
  CirclePause: "circle-pause",
  CirclePercent: "circle-percent",
  CirclePlay: "circle-play",
  CirclePlus: "circle-plus",
  CirclePower: "circle-power",
  CircleSlash: "circle-slash",
  CircleSlash2: "circle-slash-2",
  CircleSmall: "circle-small",
  CircleStop: "circle-stop",
  CircleUser: "circle-user",
  CircleUserRound: "circle-user-round",
  CircleX: "circle-x",
  CircuitBoard: "circuit-board",
  Citrus: "citrus",
  Clapperboard: "clapperboard",
  Clipboard: "clipboard",
  ClipboardCheck: "clipboard-check",
  ClipboardCopy: "clipboard-copy",
  ClipboardEdit: "clipboard-pen",
  ClipboardList: "clipboard-list",
  ClipboardMinus: "clipboard-minus",
  ClipboardPaste: "clipboard-paste",
  ClipboardPenLine: "clipboard-pen-line",
  ClipboardPlus: "clipboard-plus",
  ClipboardType: "clipboard-type",
  ClipboardX: "clipboard-x",
  Clock: "clock",
  Clock1: "clock-1",
  Clock10: "clock-10",
  Clock11: "clock-11",
  Clock12: "clock-12",
  Clock2: "clock-2",
  Clock3: "clock-3",
  Clock4: "clock-4",
  Clock5: "clock-5",
  Clock6: "clock-6",
  Clock7: "clock-7",
  Clock8: "clock-8",
  Clock9: "clock-9",
  ClockAlert: "clock-alert",
  ClockArrowDown: "clock-arrow-down",
  ClockArrowUp: "clock-arrow-up",
  Cloud: "cloud",
  CloudAlert: "cloud-alert",
  CloudCog: "cloud-cog",
  CloudDownload: "cloud-download",
  CloudDrizzle: "cloud-drizzle",
  CloudFog: "cloud-fog",
  CloudHail: "cloud-hail",
  CloudLightning: "cloud-lightning",
  CloudMoon: "cloud-moon",
  CloudMoonRain: "cloud-moon-rain",
  CloudOff: "cloud-off",
  CloudRain: "cloud-rain",
  CloudRainWind: "cloud-rain-wind",
  CloudSnow: "cloud-snow",
  CloudSun: "cloud-sun",
  CloudSunRain: "cloud-sun-rain",
  CloudUpload: "cloud-upload",
  Cloudy: "cloudy",
  Clover: "clover",
  Club: "club",
  Code: "code",
  Code2: "code-xml",
  Codepen: "codepen",
  Codesandbox: "codesandbox",
  CodeSquare: "square-code",
  Coffee: "coffee",
  Cog: "cog",
  Coins: "coins",
  Columns: "columns-2",
  Columns3: "columns-3",
  Columns4: "columns-4",
  Combine: "combine",
  Command: "command",
  Compass: "compass",
  Component: "component",
  Computer: "computer",
  ConciergeBell: "concierge-bell",
  Cone: "cone",
  Construction: "construction",
  Contact: "contact",
  Contact2: "contact-round",
  Container: "container",
  Contrast: "contrast",
  Cookie: "cookie",
  CookingPot: "cooking-pot",
  Copy: "copy",
  CopyCheck: "copy-check",
  Copyleft: "copyleft",
  CopyMinus: "copy-minus",
  CopyPlus: "copy-plus",
  Copyright: "copyright",
  CopySlash: "copy-slash",
  CopyX: "copy-x",
  CornerDownLeft: "corner-down-left",
  CornerDownRight: "corner-down-right",
  CornerLeftDown: "corner-left-down",
  CornerLeftUp: "corner-left-up",
  CornerRightDown: "corner-right-down",
  CornerRightUp: "corner-right-up",
  CornerUpLeft: "corner-up-left",
  CornerUpRight: "corner-up-right",
  Cpu: "cpu",
  CreativeCommons: "creative-commons",
  CreditCard: "credit-card",
  Croissant: "croissant",
  Crop: "crop",
  Cross: "cross",
  Crosshair: "crosshair",
  Crown: "crown",
  Cuboid: "cuboid",
  CupSoda: "cup-soda",
  Currency: "currency",
  Cylinder: "cylinder",
  Dam: "dam",
  Database: "database",
  DatabaseBackup: "database-backup",
  DatabaseZap: "database-zap",
  Delete: "delete",
  Dessert: "dessert",
  Diameter: "diameter",
  Diamond: "diamond",
  DiamondMinus: "diamond-minus",
  DiamondPercent: "diamond-percent",
  DiamondPlus: "diamond-plus",
  Dice1: "dice-1",
  Dice2: "dice-2",
  Dice3: "dice-3",
  Dice4: "dice-4",
  Dice5: "dice-5",
  Dice6: "dice-6",
  Dices: "dices",
  Diff: "diff",
  Disc: "disc",
  Disc2: "disc-2",
  Disc3: "disc-3",
  DiscAlbum: "disc-album",
  Divide: "divide",
  DivideSquare: "square-divide",
  Dna: "dna",
  DnaOff: "dna-off",
  Dock: "dock",
  Dog: "dog",
  DollarSign: "dollar-sign",
  Donut: "donut",
  DoorClosed: "door-closed",
  DoorOpen: "door-open",
  Dot: "dot",
  DotSquare: "square-dot",
  Download: "download",
  DraftingCompass: "drafting-compass",
  Drama: "drama",
  Dribbble: "dribbble",
  Drill: "drill",
  Droplet: "droplet",
  DropletOff: "droplet-off",
  Droplets: "droplets",
  Drum: "drum",
  Drumstick: "drumstick",
  Dumbbell: "dumbbell",
  Ear: "ear",
  EarOff: "ear-off",
  Earth: "earth",
  EarthLock: "earth-lock",
  Eclipse: "eclipse",
  Edit: "square-pen",
  Edit2: "pen",
  Edit3: "pen-line",
  Egg: "egg",
  EggFried: "egg-fried",
  EggOff: "egg-off",
  Ellipsis: "ellipsis",
  EllipsisVertical: "ellipsis-vertical",
  Equal: "equal",
  EqualApproximately: "equal-approximately",
  EqualNot: "equal-not",
  EqualSquare: "square-equal",
  Eraser: "eraser",
  EthernetPort: "ethernet-port",
  Euro: "euro",
  Expand: "expand",
  ExternalLink: "external-link",
  Eye: "eye",
  EyeClosed: "eye-closed",
  EyeOff: "eye-off",
  Facebook: "facebook",
  Factory: "factory",
  Fan: "fan",
  FastForward: "fast-forward",
  Feather: "feather",
  Fence: "fence",
  FerrisWheel: "ferris-wheel",
  Figma: "figma",
  File: "file",
  FileArchive: "file-archive",
  FileAudio: "file-audio",
  FileAudio2: "file-audio-2",
  FileAxis3D: "file-axis-3d",
  FileBadge: "file-badge",
  FileBadge2: "file-badge-2",
  FileBarChart: "file-chart-column-increasing",
  FileBarChart2: "file-chart-column",
  FileBox: "file-box",
  FileChartLine: "file-chart-line",
  FileChartPie: "file-chart-pie",
  FileCheck: "file-check",
  FileCheck2: "file-check-2",
  FileClock: "file-clock",
  FileCode: "file-code",
  FileCode2: "file-code-2",
  FileCog: "file-cog",
  FileDiff: "file-diff",
  FileDigit: "file-digit",
  FileDown: "file-down",
  FileEdit: "file-pen",
  FileHeart: "file-heart",
  FileImage: "file-image",
  FileInput: "file-input",
  FileJson: "file-json",
  FileJson2: "file-json-2",
  FileKey: "file-key",
  FileKey2: "file-key-2",
  FileLock: "file-lock",
  FileLock2: "file-lock-2",
  FileMinus: "file-minus",
  FileMinus2: "file-minus-2",
  FileMusic: "file-music",
  FileOutput: "file-output",
  FilePenLine: "file-pen-line",
  FilePlus: "file-plus",
  FilePlus2: "file-plus-2",
  FileQuestion: "file-question",
  Files: "files",
  FileScan: "file-scan",
  FileSearch: "file-search",
  FileSearch2: "file-search-2",
  FileSliders: "file-sliders",
  FileSpreadsheet: "file-spreadsheet",
  FileStack: "file-stack",
  FileSymlink: "file-symlink",
  FileTerminal: "file-terminal",
  FileText: "file-text",
  FileType: "file-type",
  FileType2: "file-type-2",
  FileUp: "file-up",
  FileUser: "file-user",
  FileVideo: "file-video",
  FileVideo2: "file-video-2",
  FileVolume: "file-volume",
  FileVolume2: "file-volume-2",
  FileWarning: "file-warning",
  FileX: "file-x",
  FileX2: "file-x-2",
  Film: "film",
  Filter: "filter",
  FilterX: "filter-x",
  Fingerprint: "fingerprint",
  FireExtinguisher: "fire-extinguisher",
  Fish: "fish",
  FishOff: "fish-off",
  FishSymbol: "fish-symbol",
  Flag: "flag",
  FlagOff: "flag-off",
  FlagTriangleLeft: "flag-triangle-left",
  FlagTriangleRight: "flag-triangle-right",
  Flame: "flame",
  FlameKindling: "flame-kindling",
  Flashlight: "flashlight",
  FlashlightOff: "flashlight-off",
  FlaskConical: "flask-conical",
  FlaskConicalOff: "flask-conical-off",
  FlaskRound: "flask-round",
  FlipHorizontal: "flip-horizontal",
  FlipHorizontal2: "flip-horizontal-2",
  FlipVertical: "flip-vertical",
  FlipVertical2: "flip-vertical-2",
  Flower: "flower",
  Flower2: "flower-2",
  Focus: "focus",
  Folder: "folder",
  FolderArchive: "folder-archive",
  FolderCheck: "folder-check",
  FolderClock: "folder-clock",
  FolderClosed: "folder-closed",
  FolderCode: "folder-code",
  FolderCog: "folder-cog",
  FolderDot: "folder-dot",
  FolderDown: "folder-down",
  FolderEdit: "folder-pen",
  FolderGit: "folder-git",
  FolderGit2: "folder-git-2",
  FolderHeart: "folder-heart",
  FolderInput: "folder-input",
  FolderKanban: "folder-kanban",
  FolderKey: "folder-key",
  FolderLock: "folder-lock",
  FolderMinus: "folder-minus",
  FolderOpen: "folder-open",
  FolderOpenDot: "folder-open-dot",
  FolderOutput: "folder-output",
  FolderPlus: "folder-plus",
  FolderRoot: "folder-root",
  Folders: "folders",
  FolderSearch: "folder-search",
  FolderSearch2: "folder-search-2",
  FolderSymlink: "folder-symlink",
  FolderSync: "folder-sync",
  FolderTree: "folder-tree",
  FolderUp: "folder-up",
  FolderX: "folder-x",
  FoldHorizontal: "fold-horizontal",
  FoldVertical: "fold-vertical",
  Footprints: "footprints",
  ForkKnife: "utensils",
  ForkKnifeCrossed: "utensils-crossed",
  Forklift: "forklift",
  FormInput: "rectangle-ellipsis",
  Forward: "forward",
  Frame: "frame",
  Framer: "framer",
  Frown: "frown",
  Fuel: "fuel",
  Fullscreen: "fullscreen",
  FunctionSquare: "square-function",
  GalleryHorizontal: "gallery-horizontal",
  GalleryHorizontalEnd: "gallery-horizontal-end",
  GalleryThumbnails: "gallery-thumbnails",
  GalleryVertical: "gallery-vertical",
  GalleryVerticalEnd: "gallery-vertical-end",
  Gamepad: "gamepad",
  Gamepad2: "gamepad-2",
  GanttChartSquare: "square-chart-gantt",
  Gauge: "gauge",
  Gavel: "gavel",
  Gem: "gem",
  Ghost: "ghost",
  Gift: "gift",
  GitBranch: "git-branch",
  GitBranchPlus: "git-branch-plus",
  GitCommit: "git-commit-horizontal",
  GitCommitVertical: "git-commit-vertical",
  GitCompare: "git-compare",
  GitCompareArrows: "git-compare-arrows",
  GitFork: "git-fork",
  GitGraph: "git-graph",
  Github: "github",
  Gitlab: "gitlab",
  GitMerge: "git-merge",
  GitPullRequest: "git-pull-request",
  GitPullRequestArrow: "git-pull-request-arrow",
  GitPullRequestClosed: "git-pull-request-closed",
  GitPullRequestCreate: "git-pull-request-create",
  GitPullRequestCreateArrow: "git-pull-request-create-arrow",
  GitPullRequestDraft: "git-pull-request-draft",
  Glasses: "glasses",
  GlassWater: "glass-water",
  Globe: "globe",
  GlobeLock: "globe-lock",
  Goal: "goal",
  Grab: "grab",
  GraduationCap: "graduation-cap",
  Grape: "grape",
  Grid: "grid-3x3",
  Grid2X2: "grid-2x2",
  Grid2X2Check: "grid-2x2-check",
  Grid2X2Plus: "grid-2x2-plus",
  Grid2X2X: "grid-2x2-x",
  Grip: "grip",
  GripHorizontal: "grip-horizontal",
  GripVertical: "grip-vertical",
  Group: "group",
  Guitar: "guitar",
  Ham: "ham",
  Hammer: "hammer",
  Hand: "hand",
  HandCoins: "hand-coins",
  HandHeart: "hand-heart",
  HandHelping: "hand-helping",
  HandMetal: "hand-metal",
  HandPlatter: "hand-platter",
  Handshake: "handshake",
  HardDrive: "hard-drive",
  HardDriveDownload: "hard-drive-download",
  HardDriveUpload: "hard-drive-upload",
  HardHat: "hard-hat",
  Hash: "hash",
  Haze: "haze",
  HdmiPort: "hdmi-port",
  Heading: "heading",
  Heading1: "heading-1",
  Heading2: "heading-2",
  Heading3: "heading-3",
  Heading4: "heading-4",
  Heading5: "heading-5",
  Heading6: "heading-6",
  HeadphoneOff: "headphone-off",
  Headphones: "headphones",
  Headset: "headset",
  Heart: "heart",
  HeartCrack: "heart-crack",
  HeartHandshake: "heart-handshake",
  HeartOff: "heart-off",
  HeartPulse: "heart-pulse",
  Heater: "heater",
  Hexagon: "hexagon",
  Highlighter: "highlighter",
  History: "history",
  Home: "house",
  Hop: "hop",
  HopOff: "hop-off",
  Hospital: "hospital",
  Hotel: "hotel",
  Hourglass: "hourglass",
  HousePlug: "house-plug",
  HousePlus: "house-plus",
  HouseWifi: "house-wifi",
  IceCream: "ice-cream-cone",
  IceCream2: "ice-cream-bowl",
  IdCard: "id-card",
  Image: "image",
  ImageDown: "image-down",
  ImageMinus: "image-minus",
  ImageOff: "image-off",
  ImagePlay: "image-play",
  ImagePlus: "image-plus",
  Images: "images",
  ImageUp: "image-up",
  ImageUpscale: "image-upscale",
  Import: "import",
  Inbox: "inbox",
  Indent: "indent-increase",
  IndentDecrease: "indent-decrease",
  IndianRupee: "indian-rupee",
  Infinity: "infinity",
  Info: "info",
  Inspect: "square-mouse-pointer",
  InspectionPanel: "inspection-panel",
  Instagram: "instagram",
  Italic: "italic",
  IterationCcw: "iteration-ccw",
  IterationCw: "iteration-cw",
  JapaneseYen: "japanese-yen",
  Joystick: "joystick",
  Kanban: "kanban",
  KanbanSquare: "square-kanban",
  KanbanSquareDashed: "square-dashed-kanban",
  Key: "key",
  Keyboard: "keyboard",
  KeyboardMusic: "keyboard-music",
  KeyboardOff: "keyboard-off",
  KeyRound: "key-round",
  KeySquare: "key-square",
  Lamp: "lamp",
  LampCeiling: "lamp-ceiling",
  LampDesk: "lamp-desk",
  LampFloor: "lamp-floor",
  LampWallDown: "lamp-wall-down",
  LampWallUp: "lamp-wall-up",
  Landmark: "landmark",
  LandPlot: "land-plot",
  Languages: "languages",
  Laptop: "laptop",
  Laptop2: "laptop-minimal",
  LaptopMinimalCheck: "laptop-minimal-check",
  Lasso: "lasso",
  LassoSelect: "lasso-select",
  Laugh: "laugh",
  Layers: "layers",
  Layers2: "layers-2",
  Layout: "panels-top-left",
  LayoutDashboard: "layout-dashboard",
  LayoutGrid: "layout-grid",
  LayoutList: "layout-list",
  LayoutPanelLeft: "layout-panel-left",
  LayoutPanelTop: "layout-panel-top",
  LayoutTemplate: "layout-template",
  Leaf: "leaf",
  LeafyGreen: "leafy-green",
  Lectern: "lectern",
  LetterText: "letter-text",
  Library: "library",
  LibraryBig: "library-big",
  LibrarySquare: "square-library",
  LifeBuoy: "life-buoy",
  Ligature: "ligature",
  Lightbulb: "lightbulb",
  LightbulbOff: "lightbulb-off",
  Link: "link",
  Link2: "link-2",
  Link2Off: "link-2-off",
  Linkedin: "linkedin",
  List: "list",
  ListCheck: "list-check",
  ListChecks: "list-checks",
  ListCollapse: "list-collapse",
  ListEnd: "list-end",
  ListFilter: "list-filter",
  ListFilterPlus: "list-filter-plus",
  ListMinus: "list-minus",
  ListMusic: "list-music",
  ListOrdered: "list-ordered",
  ListPlus: "list-plus",
  ListRestart: "list-restart",
  ListStart: "list-start",
  ListTodo: "list-todo",
  ListTree: "list-tree",
  ListVideo: "list-video",
  ListX: "list-x",
  Loader: "loader",
  Loader2: "loader-circle",
  LoaderPinwheel: "loader-pinwheel",
  Locate: "locate",
  LocateFixed: "locate-fixed",
  LocateOff: "locate-off",
  Lock: "lock",
  LockKeyhole: "lock-keyhole",
  LockKeyholeOpen: "lock-keyhole-open",
  LockOpen: "lock-open",
  LogIn: "log-in",
  LogOut: "log-out",
  Logs: "logs",
  Lollipop: "lollipop",
  Luggage: "luggage",
  Magnet: "magnet",
  Mail: "mail",
  Mailbox: "mailbox",
  MailCheck: "mail-check",
  MailMinus: "mail-minus",
  MailOpen: "mail-open",
  MailPlus: "mail-plus",
  MailQuestion: "mail-question",
  Mails: "mails",
  MailSearch: "mail-search",
  MailWarning: "mail-warning",
  MailX: "mail-x",
  Map: "map",
  MapPin: "map-pin",
  MapPinCheck: "map-pin-check",
  MapPinCheckInside: "map-pin-check-inside",
  MapPinHouse: "map-pin-house",
  MapPinMinus: "map-pin-minus",
  MapPinMinusInside: "map-pin-minus-inside",
  MapPinned: "map-pinned",
  MapPinOff: "map-pin-off",
  MapPinPlus: "map-pin-plus",
  MapPinPlusInside: "map-pin-plus-inside",
  MapPinX: "map-pin-x",
  MapPinXInside: "map-pin-x-inside",
  MapPlus: "map-plus",
  Mars: "mars",
  MarsStroke: "mars-stroke",
  Martini: "martini",
  Maximize: "maximize",
  Maximize2: "maximize-2",
  Medal: "medal",
  Megaphone: "megaphone",
  MegaphoneOff: "megaphone-off",
  Meh: "meh",
  MemoryStick: "memory-stick",
  Menu: "menu",
  MenuSquare: "square-menu",
  Merge: "merge",
  MessageCircle: "message-circle",
  MessageCircleCode: "message-circle-code",
  MessageCircleDashed: "message-circle-dashed",
  MessageCircleHeart: "message-circle-heart",
  MessageCircleMore: "message-circle-more",
  MessageCircleOff: "message-circle-off",
  MessageCirclePlus: "message-circle-plus",
  MessageCircleQuestion: "message-circle-question",
  MessageCircleReply: "message-circle-reply",
  MessageCircleWarning: "message-circle-warning",
  MessageCircleX: "message-circle-x",
  MessageSquare: "message-square",
  MessageSquareCode: "message-square-code",
  MessageSquareDashed: "message-square-dashed",
  MessageSquareDiff: "message-square-diff",
  MessageSquareDot: "message-square-dot",
  MessageSquareHeart: "message-square-heart",
  MessageSquareLock: "message-square-lock",
  MessageSquareMore: "message-square-more",
  MessageSquareOff: "message-square-off",
  MessageSquarePlus: "message-square-plus",
  MessageSquareQuote: "message-square-quote",
  MessageSquareReply: "message-square-reply",
  MessageSquareShare: "message-square-share",
  MessageSquareText: "message-square-text",
  MessageSquareWarning: "message-square-warning",
  MessageSquareX: "message-square-x",
  MessagesSquare: "messages-square",
  Mic: "mic",
  Mic2: "mic-vocal",
  MicOff: "mic-off",
  Microchip: "microchip",
  Microscope: "microscope",
  Microwave: "microwave",
  Milestone: "milestone",
  Milk: "milk",
  MilkOff: "milk-off",
  Minimize: "minimize",
  Minimize2: "minimize-2",
  Minus: "minus",
  MinusSquare: "square-minus",
  Monitor: "monitor",
  MonitorCheck: "monitor-check",
  MonitorCog: "monitor-cog",
  MonitorDot: "monitor-dot",
  MonitorDown: "monitor-down",
  MonitorOff: "monitor-off",
  MonitorPause: "monitor-pause",
  MonitorPlay: "monitor-play",
  MonitorSmartphone: "monitor-smartphone",
  MonitorSpeaker: "monitor-speaker",
  MonitorStop: "monitor-stop",
  MonitorUp: "monitor-up",
  MonitorX: "monitor-x",
  Moon: "moon",
  MoonStar: "moon-star",
  Mountain: "mountain",
  MountainSnow: "mountain-snow",
  Mouse: "mouse",
  MouseOff: "mouse-off",
  MousePointer: "mouse-pointer",
  MousePointer2: "mouse-pointer-2",
  MousePointerBan: "mouse-pointer-ban",
  MousePointerClick: "mouse-pointer-click",
  MousePointerSquareDashed: "square-dashed-mouse-pointer",
  Move: "move",
  Move3D: "move-3d",
  MoveDiagonal: "move-diagonal",
  MoveDiagonal2: "move-diagonal-2",
  MoveDown: "move-down",
  MoveDownLeft: "move-down-left",
  MoveDownRight: "move-down-right",
  MoveHorizontal: "move-horizontal",
  MoveLeft: "move-left",
  MoveRight: "move-right",
  MoveUp: "move-up",
  MoveUpLeft: "move-up-left",
  MoveUpRight: "move-up-right",
  MoveVertical: "move-vertical",
  MSquare: "square-m",
  Music: "music",
  Music2: "music-2",
  Music3: "music-3",
  Music4: "music-4",
  Navigation: "navigation",
  Navigation2: "navigation-2",
  Navigation2Off: "navigation-2-off",
  NavigationOff: "navigation-off",
  Network: "network",
  Newspaper: "newspaper",
  Nfc: "nfc",
  NonBinary: "non-binary",
  Notebook: "notebook",
  NotebookPen: "notebook-pen",
  NotebookTabs: "notebook-tabs",
  NotebookText: "notebook-text",
  NotepadText: "notepad-text",
  NotepadTextDashed: "notepad-text-dashed",
  Nut: "nut",
  NutOff: "nut-off",
  Octagon: "octagon",
  OctagonMinus: "octagon-minus",
  OctagonPause: "octagon-pause",
  OctagonX: "octagon-x",
  Omega: "omega",
  Option: "option",
  Orbit: "orbit",
  Origami: "origami",
  Package: "package",
  Package2: "package-2",
  PackageCheck: "package-check",
  PackageMinus: "package-minus",
  PackageOpen: "package-open",
  PackagePlus: "package-plus",
  PackageSearch: "package-search",
  PackageX: "package-x",
  Paintbrush: "paintbrush",
  Paintbrush2: "paintbrush-vertical",
  PaintBucket: "paint-bucket",
  PaintRoller: "paint-roller",
  Palette: "palette",
  Palmtree: "tree-palm",
  PanelBottom: "panel-bottom",
  PanelBottomClose: "panel-bottom-close",
  PanelBottomDashed: "panel-bottom-dashed",
  PanelBottomOpen: "panel-bottom-open",
  PanelLeft: "panel-left",
  PanelLeftClose: "panel-left-close",
  PanelLeftDashed: "panel-left-dashed",
  PanelLeftOpen: "panel-left-open",
  PanelRight: "panel-right",
  PanelRightClose: "panel-right-close",
  PanelRightDashed: "panel-right-dashed",
  PanelRightOpen: "panel-right-open",
  PanelsLeftBottom: "panels-left-bottom",
  PanelsRightBottom: "panels-right-bottom",
  PanelsTopBottom: "rows-3",
  PanelTop: "panel-top",
  PanelTopClose: "panel-top-close",
  PanelTopDashed: "panel-top-dashed",
  PanelTopOpen: "panel-top-open",
  Paperclip: "paperclip",
  Parentheses: "parentheses",
  ParkingMeter: "parking-meter",
  ParkingSquare: "square-parking",
  ParkingSquareOff: "square-parking-off",
  PartyPopper: "party-popper",
  Pause: "pause",
  PawPrint: "paw-print",
  PcCase: "pc-case",
  Pencil: "pencil",
  PencilLine: "pencil-line",
  PencilOff: "pencil-off",
  PencilRuler: "pencil-ruler",
  PenOff: "pen-off",
  Pentagon: "pentagon",
  PenTool: "pen-tool",
  Percent: "percent",
  PercentSquare: "square-percent",
  PersonStanding: "person-standing",
  PhilippinePeso: "philippine-peso",
  Phone: "phone",
  PhoneCall: "phone-call",
  PhoneForwarded: "phone-forwarded",
  PhoneIncoming: "phone-incoming",
  PhoneMissed: "phone-missed",
  PhoneOff: "phone-off",
  PhoneOutgoing: "phone-outgoing",
  Pi: "pi",
  Piano: "piano",
  Pickaxe: "pickaxe",
  PictureInPicture: "picture-in-picture",
  PictureInPicture2: "picture-in-picture-2",
  PiggyBank: "piggy-bank",
  Pilcrow: "pilcrow",
  PilcrowLeft: "pilcrow-left",
  PilcrowRight: "pilcrow-right",
  PilcrowSquare: "square-pilcrow",
  Pill: "pill",
  PillBottle: "pill-bottle",
  Pin: "pin",
  PinOff: "pin-off",
  Pipette: "pipette",
  PiSquare: "square-pi",
  Pizza: "pizza",
  Plane: "plane",
  PlaneLanding: "plane-landing",
  PlaneTakeoff: "plane-takeoff",
  Play: "play",
  PlaySquare: "square-play",
  Plug: "plug",
  Plug2: "plug-2",
  PlugZap: "plug-zap",
  Plus: "plus",
  PlusSquare: "square-plus",
  Pocket: "pocket",
  PocketKnife: "pocket-knife",
  Podcast: "podcast",
  Pointer: "pointer",
  PointerOff: "pointer-off",
  Popcorn: "popcorn",
  Popsicle: "popsicle",
  PoundSterling: "pound-sterling",
  Power: "power",
  PowerOff: "power-off",
  PowerSquare: "square-power",
  Presentation: "presentation",
  Printer: "printer",
  PrinterCheck: "printer-check",
  Projector: "projector",
  Proportions: "proportions",
  Puzzle: "puzzle",
  Pyramid: "pyramid",
  QrCode: "qr-code",
  Quote: "quote",
  Rabbit: "rabbit",
  Radar: "radar",
  Radiation: "radiation",
  Radical: "radical",
  Radio: "radio",
  RadioReceiver: "radio-receiver",
  RadioTower: "radio-tower",
  Radius: "radius",
  RailSymbol: "rail-symbol",
  Rainbow: "rainbow",
  Rat: "rat",
  Ratio: "ratio",
  Receipt: "receipt",
  ReceiptCent: "receipt-cent",
  ReceiptEuro: "receipt-euro",
  ReceiptIndianRupee: "receipt-indian-rupee",
  ReceiptJapaneseYen: "receipt-japanese-yen",
  ReceiptPoundSterling: "receipt-pound-sterling",
  ReceiptRussianRuble: "receipt-russian-ruble",
  ReceiptSwissFranc: "receipt-swiss-franc",
  ReceiptText: "receipt-text",
  RectangleHorizontal: "rectangle-horizontal",
  RectangleVertical: "rectangle-vertical",
  Recycle: "recycle",
  Redo: "redo",
  Redo2: "redo-2",
  RedoDot: "redo-dot",
  RefreshCcw: "refresh-ccw",
  RefreshCcwDot: "refresh-ccw-dot",
  RefreshCw: "refresh-cw",
  RefreshCwOff: "refresh-cw-off",
  Refrigerator: "refrigerator",
  Regex: "regex",
  RemoveFormatting: "remove-formatting",
  Repeat: "repeat",
  Repeat1: "repeat-1",
  Repeat2: "repeat-2",
  Replace: "replace",
  ReplaceAll: "replace-all",
  Reply: "reply",
  ReplyAll: "reply-all",
  Rewind: "rewind",
  Ribbon: "ribbon",
  Rocket: "rocket",
  RockingChair: "rocking-chair",
  RollerCoaster: "roller-coaster",
  Rotate3D: "rotate-3d",
  RotateCcw: "rotate-ccw",
  RotateCcwSquare: "rotate-ccw-square",
  RotateCw: "rotate-cw",
  RotateCwSquare: "rotate-cw-square",
  Route: "route",
  RouteOff: "route-off",
  Router: "router",
  Rows: "rows-2",
  Rows4: "rows-4",
  Rss: "rss",
  Ruler: "ruler",
  RussianRuble: "russian-ruble",
  Sailboat: "sailboat",
  Salad: "salad",
  Sandwich: "sandwich",
  Satellite: "satellite",
  SatelliteDish: "satellite-dish",
  Save: "save",
  SaveAll: "save-all",
  SaveOff: "save-off",
  Scale: "scale",
  Scale3D: "scale-3d",
  Scaling: "scaling",
  Scan: "scan",
  ScanBarcode: "scan-barcode",
  ScanEye: "scan-eye",
  ScanFace: "scan-face",
  ScanHeart: "scan-heart",
  ScanLine: "scan-line",
  ScanQrCode: "scan-qr-code",
  ScanSearch: "scan-search",
  ScanText: "scan-text",
  School: "school",
  School2: "university",
  Scissors: "scissors",
  ScissorsLineDashed: "scissors-line-dashed",
  ScissorsSquare: "square-scissors",
  ScissorsSquareDashedBottom: "square-bottom-dashed-scissors",
  ScreenShare: "screen-share",
  ScreenShareOff: "screen-share-off",
  Scroll: "scroll",
  ScrollText: "scroll-text",
  Search: "search",
  SearchCheck: "search-check",
  SearchCode: "search-code",
  SearchSlash: "search-slash",
  SearchX: "search-x",
  Section: "section",
  Send: "send",
  SendHorizonal: "send-horizontal",
  SendToBack: "send-to-back",
  SeparatorHorizontal: "separator-horizontal",
  SeparatorVertical: "separator-vertical",
  Server: "server",
  ServerCog: "server-cog",
  ServerCrash: "server-crash",
  ServerOff: "server-off",
  Settings: "settings",
  Settings2: "settings-2",
  Shapes: "shapes",
  Share: "share",
  Share2: "share-2",
  Sheet: "sheet",
  Shell: "shell",
  Shield: "shield",
  ShieldAlert: "shield-alert",
  ShieldBan: "shield-ban",
  ShieldCheck: "shield-check",
  ShieldClose: "shield-x",
  ShieldEllipsis: "shield-ellipsis",
  ShieldHalf: "shield-half",
  ShieldMinus: "shield-minus",
  ShieldOff: "shield-off",
  ShieldPlus: "shield-plus",
  ShieldQuestion: "shield-question",
  ShieldUser: "shield-user",
  Ship: "ship",
  ShipWheel: "ship-wheel",
  Shirt: "shirt",
  ShoppingBag: "shopping-bag",
  ShoppingBasket: "shopping-basket",
  ShoppingCart: "shopping-cart",
  Shovel: "shovel",
  ShowerHead: "shower-head",
  Shrink: "shrink",
  Shrub: "shrub",
  Shuffle: "shuffle",
  Sigma: "sigma",
  SigmaSquare: "square-sigma",
  Signal: "signal",
  SignalHigh: "signal-high",
  SignalLow: "signal-low",
  SignalMedium: "signal-medium",
  SignalZero: "signal-zero",
  Signature: "signature",
  Signpost: "signpost",
  SignpostBig: "signpost-big",
  Siren: "siren",
  SkipBack: "skip-back",
  SkipForward: "skip-forward",
  Skull: "skull",
  Slack: "slack",
  Slash: "slash",
  SlashSquare: "square-slash",
  Slice: "slice",
  Sliders: "sliders-vertical",
  SlidersHorizontal: "sliders-horizontal",
  Smartphone: "smartphone",
  SmartphoneCharging: "smartphone-charging",
  SmartphoneNfc: "smartphone-nfc",
  Smile: "smile",
  SmilePlus: "smile-plus",
  Snail: "snail",
  Snowflake: "snowflake",
  Sofa: "sofa",
  Soup: "soup",
  Space: "space",
  Spade: "spade",
  Sparkle: "sparkle",
  Sparkles: "sparkles",
  Speaker: "speaker",
  Speech: "speech",
  SpellCheck: "spell-check",
  SpellCheck2: "spell-check-2",
  Spline: "spline",
  Split: "split",
  SplitSquareHorizontal: "square-split-horizontal",
  SplitSquareVertical: "square-split-vertical",
  SprayCan: "spray-can",
  Sprout: "sprout",
  Square: "square",
  SquareDashedBottom: "square-dashed-bottom",
  SquareDashedBottomCode: "square-dashed-bottom-code",
  SquareRadical: "square-radical",
  SquareRoundCorner: "square-round-corner",
  SquareSquare: "square-square",
  SquareStack: "square-stack",
  SquareTerminal: "square-terminal",
  SquareUser: "square-user",
  SquareUserRound: "square-user-round",
  SquareX: "square-x",
  Squircle: "squircle",
  Squirrel: "squirrel",
  Stamp: "stamp",
  Star: "star",
  StarHalf: "star-half",
  StarOff: "star-off",
  StepBack: "step-back",
  StepForward: "step-forward",
  Stethoscope: "stethoscope",
  Sticker: "sticker",
  StickyNote: "sticky-note",
  Store: "store",
  StretchHorizontal: "stretch-horizontal",
  StretchVertical: "stretch-vertical",
  Strikethrough: "strikethrough",
  Subscript: "subscript",
  Sun: "sun",
  SunDim: "sun-dim",
  SunMedium: "sun-medium",
  SunMoon: "sun-moon",
  Sunrise: "sunrise",
  Sunset: "sunset",
  SunSnow: "sun-snow",
  Superscript: "superscript",
  SwatchBook: "swatch-book",
  SwissFranc: "swiss-franc",
  SwitchCamera: "switch-camera",
  Sword: "sword",
  Swords: "swords",
  Syringe: "syringe",
  Table: "table",
  Table2: "table-2",
  TableCellsMerge: "table-cells-merge",
  TableCellsSplit: "table-cells-split",
  TableColumnsSplit: "table-columns-split",
  TableOfContents: "table-of-contents",
  TableProperties: "table-properties",
  TableRowsSplit: "table-rows-split",
  Tablet: "tablet",
  Tablets: "tablets",
  TabletSmartphone: "tablet-smartphone",
  Tag: "tag",
  Tags: "tags",
  Tally1: "tally-1",
  Tally2: "tally-2",
  Tally3: "tally-3",
  Tally4: "tally-4",
  Tally5: "tally-5",
  Tangent: "tangent",
  Target: "target",
  Telescope: "telescope",
  Tent: "tent",
  TentTree: "tent-tree",
  Terminal: "terminal",
  TestTube: "test-tube",
  TestTube2: "test-tube-diagonal",
  TestTubes: "test-tubes",
  Text: "text",
  TextCursor: "text-cursor",
  TextCursorInput: "text-cursor-input",
  TextQuote: "text-quote",
  TextSearch: "text-search",
  TextSelect: "text-select",
  Theater: "theater",
  Thermometer: "thermometer",
  ThermometerSnowflake: "thermometer-snowflake",
  ThermometerSun: "thermometer-sun",
  ThumbsDown: "thumbs-down",
  ThumbsUp: "thumbs-up",
  Ticket: "ticket",
  TicketCheck: "ticket-check",
  TicketMinus: "ticket-minus",
  TicketPercent: "ticket-percent",
  TicketPlus: "ticket-plus",
  Tickets: "tickets",
  TicketSlash: "ticket-slash",
  TicketsPlane: "tickets-plane",
  TicketX: "ticket-x",
  Timer: "timer",
  TimerOff: "timer-off",
  TimerReset: "timer-reset",
  ToggleLeft: "toggle-left",
  ToggleRight: "toggle-right",
  Toilet: "toilet",
  Tornado: "tornado",
  Torus: "torus",
  Touchpad: "touchpad",
  TouchpadOff: "touchpad-off",
  TowerControl: "tower-control",
  ToyBrick: "toy-brick",
  Tractor: "tractor",
  TrafficCone: "traffic-cone",
  Train: "tram-front",
  TrainFront: "train-front",
  TrainFrontTunnel: "train-front-tunnel",
  TrainTrack: "train-track",
  Transgender: "transgender",
  Trash: "trash",
  Trash2: "trash-2",
  TreeDeciduous: "tree-deciduous",
  TreePine: "tree-pine",
  Trees: "trees",
  Trello: "trello",
  TrendingDown: "trending-down",
  TrendingUp: "trending-up",
  TrendingUpDown: "trending-up-down",
  Triangle: "triangle",
  TriangleDashed: "triangle-dashed",
  TriangleRight: "triangle-right",
  Trophy: "trophy",
  Truck: "truck",
  Turtle: "turtle",
  Tv: "tv",
  Tv2: "tv-minimal",
  TvMinimalPlay: "tv-minimal-play",
  Twitch: "twitch",
  Twitter: "twitter",
  Type: "type",
  TypeOutline: "type-outline",
  Umbrella: "umbrella",
  UmbrellaOff: "umbrella-off",
  Underline: "underline",
  Undo: "undo",
  Undo2: "undo-2",
  UndoDot: "undo-dot",
  UnfoldHorizontal: "unfold-horizontal",
  UnfoldVertical: "unfold-vertical",
  Ungroup: "ungroup",
  Unlink: "unlink",
  Unlink2: "unlink-2",
  Unplug: "unplug",
  Upload: "upload",
  Usb: "usb",
  User: "user",
  User2: "user-round",
  UserCheck: "user-check",
  UserCheck2: "user-round-check",
  UserCog: "user-cog",
  UserCog2: "user-round-cog",
  UserMinus: "user-minus",
  UserMinus2: "user-round-minus",
  UserPen: "user-pen",
  UserPlus: "user-plus",
  UserPlus2: "user-round-plus",
  UserRoundPen: "user-round-pen",
  UserRoundSearch: "user-round-search",
  UserRoundX: "user-round-x",
  Users: "users",
  Users2: "users-round",
  UserSearch: "user-search",
  UserX: "user-x",
  UtilityPole: "utility-pole",
  Variable: "variable",
  Vault: "vault",
  Vegan: "vegan",
  VenetianMask: "venetian-mask",
  Venus: "venus",
  VenusAndMars: "venus-and-mars",
  Vibrate: "vibrate",
  VibrateOff: "vibrate-off",
  Video: "video",
  VideoOff: "video-off",
  Videotape: "videotape",
  View: "view",
  Voicemail: "voicemail",
  Volleyball: "volleyball",
  Volume: "volume",
  Volume1: "volume-1",
  Volume2: "volume-2",
  VolumeOff: "volume-off",
  VolumeX: "volume-x",
  Vote: "vote",
  Wallet: "wallet",
  Wallet2: "wallet-minimal",
  WalletCards: "wallet-cards",
  Wallpaper: "wallpaper",
  Wand: "wand",
  Wand2: "wand-sparkles",
  Warehouse: "warehouse",
  WashingMachine: "washing-machine",
  Watch: "watch",
  Waves: "waves",
  WavesLadder: "waves-ladder",
  Waypoints: "waypoints",
  Webcam: "webcam",
  Webhook: "webhook",
  WebhookOff: "webhook-off",
  Weight: "weight",
  Wheat: "wheat",
  WheatOff: "wheat-off",
  WholeWord: "whole-word",
  Wifi: "wifi",
  WifiHigh: "wifi-high",
  WifiLow: "wifi-low",
  WifiOff: "wifi-off",
  WifiZero: "wifi-zero",
  Wind: "wind",
  WindArrowDown: "wind-arrow-down",
  Wine: "wine",
  WineOff: "wine-off",
  Workflow: "workflow",
  Worm: "worm",
  WrapText: "wrap-text",
  Wrench: "wrench",
  X: "x",
  Youtube: "youtube",
  Zap: "zap",
  ZapOff: "zap-off",
  ZoomIn: "zoom-in",
  ZoomOut: "zoom-out",
};
