/**
 * Render every email to disk for review.
 *
 * `npm run email:preview` writes one HTML file per fixture into
 * `.email-preview/`, plus an index that stacks them all in iframes. Each file
 * is the exact HTML the transport would send — same `renderFor`, same shell —
 * so what you scroll through is what lands in the inbox, short of the client's
 * own quirks.
 *
 * The messages come from `email-fixtures.ts`, the same registry the test suite
 * asserts over, so a template becomes visible here and verified there in one
 * step. The site's real configuration is read from the database, falling back
 * to defaults without one.
 *
 * Everything runs inside `main()` because the project emits CommonJS, where
 * top-level `await` is a syntax error.
 */

import "dotenv/config";

import { mkdirSync, writeFileSync, rmSync } from "node:fs";
import { join } from "node:path";

import { FIXTURES, previewContext } from "./email-fixtures";
import { esc } from "../src/lib/email/blocks";
import { renderFor } from "../src/lib/email/send";
import { buildTheme } from "../src/lib/email/tokens";

async function main() {
  const { ctx, source } = await previewContext();
  const t = buildTheme(ctx.branding);

  const entries = FIXTURES.map((fixture) => {
    const message = fixture.build(ctx);
    return { ...fixture, message, html: renderFor(ctx, message) };
  });

  const OUT = join(process.cwd(), ".email-preview");
  rmSync(OUT, { recursive: true, force: true });
  mkdirSync(OUT, { recursive: true });

  for (const entry of entries) {
    writeFileSync(join(OUT, `${entry.id}.html`), entry.html, "utf8");
  }

  // The index. Deliberately dark and neutral so it cannot be mistaken for part
  // of the design being judged.
  const index = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>Email preview — ${esc(ctx.siteName)}</title>
<style>
  :root { color-scheme: dark; }
  * { box-sizing: border-box; }
  body {
    margin: 0; padding: 40px 24px 80px;
    background: #0b0b0d; color: #e8e8ea;
    font: 14px/1.5 ui-sans-serif, system-ui, -apple-system, "Segoe UI", sans-serif;
  }
  .wrap { max-width: 700px; margin: 0 auto; }
  h1 { font-size: 20px; font-weight: 800; letter-spacing: -0.02em; margin: 0 0 6px; }
  .sub { color: #8a8a92; font-size: 13px; margin: 0 0 36px; }
  .brand { display:inline-block; width:10px; height:10px; border-radius:99px;
           background:${t.primary}; vertical-align:-1px; margin-right:7px; }
  .empty { border:1px dashed #33333c; border-radius:12px; padding:28px; color:#8a8a92; text-align:center; }
  article { margin: 0 0 44px; }
  .meta { display:flex; align-items:baseline; gap:10px; flex-wrap:wrap; margin:0 0 4px; }
  .group { font-size:10px; font-weight:700; letter-spacing:0.18em; text-transform:uppercase; color:#8a8a92; }
  .name  { font-family: ui-monospace, Consolas, monospace; font-size:13px; color:#e8e8ea; }
  .subject { color:#b8b8c0; font-size:13px; margin:0 0 12px; }
  .subject b { color:#e8e8ea; font-weight:600; }
  iframe { width:100%; height:1200px; border:1px solid #26262c; border-radius:12px; background:#fff; display:block; }
  footer { color:#5a5a62; font-size:12px; text-align:center; margin-top:60px; }
</style>
</head>
<body>
<div class="wrap">
  <h1><span class="brand"></span>Email preview</h1>
  <p class="sub">
    ${entries.length} message${entries.length === 1 ? "" : "s"} · brand
    <code>${esc(t.primary)}</code> from ${esc(source)} · bands
    <code>${esc(t.bandA)}</code> and <code>${esc(t.bandB)}</code> · rendered by
    <code>renderFor</code>, exactly as sent.
    <br />Set <code>PREVIEW_BRAND</code> to check the palette at another brand colour.
  </p>
  ${
    entries.length === 0
      ? `<p class="empty">No fixtures yet — templates appear here as they are converted.</p>`
      : entries
          .map(
            (e) => `<article>
    <div class="meta"><span class="group">${esc(e.group)}</span><span class="name">${esc(e.name)}</span></div>
    <p class="subject"><b>${esc(e.message.subject)}</b> — ${esc(e.message.previewText)}</p>
    <iframe src="./${e.id}.html" title="${esc(e.name)}" loading="lazy"></iframe>
  </article>`
          )
          .join("\n  ")
  }
  <footer>Generated by scripts/email-preview.ts</footer>
</div>
</body>
</html>`;

  writeFileSync(join(OUT, "index.html"), index, "utf8");

  console.log(`\n  ${entries.length + 1} files written to .email-preview/`);
  console.log(`  brand ${t.primary} from ${source}\n`);
  console.log(`  open .email-preview/index.html\n`);
  for (const e of entries) console.log(`    ${e.group.padEnd(12)} ${e.name}`);
  console.log("");
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
